# Generated by Django 4.2.6 on 2023-10-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falloutRpg', '0003_alter_perk_skill_1_name_alter_perk_skill_2_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perk',
            old_name='special_skill_req',
            new_name='special_1_req',
        ),
        migrations.RenameField(
            model_name='perk',
            old_name='special_skill_name',
            new_name='special_skill_1_name',
        ),
        migrations.AddField(
            model_name='perk',
            name='special_2_req',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perk',
            name='special_skill_2_name',
            field=models.CharField(choices=[('ST', 'Strength'), ('PE', 'Perception'), ('EN', 'Endurance'), ('CH', 'Charisma'), ('IN', 'Intelligence'), ('AG', 'Agility'), ('LU', 'Luck'), ('NA', 'Not Required')], default='NA', max_length=2),
        ),
    ]
