# Generated by Django 4.2.6 on 2023-10-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falloutRpg', '0004_rename_special_skill_req_perk_special_1_req_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.CharField(default='admin', max_length=64),
        ),
    ]
