# Generated by Django 4.2.6 on 2023-10-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falloutRpg', '0005_character_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
