# Generated by Django 4.2.6 on 2023-10-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('falloutRpg', '0007_alter_inventory_item_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory_item',
            old_name='owner_inventory',
            new_name='owner',
        ),
    ]
