# Generated by Django 4.2.6 on 2023-10-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falloutRpg', '0008_rename_owner_inventory_inventory_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='karma',
            field=models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Neutral', 'Neutral'), ('Evil', 'Evil'), ('Very Evil', 'Very Evil')], default='Neutral', max_length=20),
        ),
    ]
