# Generated by Django 4.2.6 on 2023-10-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falloutRpg', '0009_alter_character_karma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armor',
            name='type',
            field=models.CharField(choices=[('Unarmored', 'Unarmored'), ('Light', 'Light'), ('Medium', 'Medium'), ('Heavy', 'Heavy')], default='Unarmored', max_length=64),
        ),
        migrations.AlterField(
            model_name='character',
            name='karma',
            field=models.CharField(choices=[('Very Good', 'Very Good'), ('Good', 'Good'), ('Neutral', 'Neutral'), ('Evil', 'Evil'), ('Very Evil', 'Very Evil')], default='Neutral', max_length=64),
        ),
        migrations.AlterField(
            model_name='perk',
            name='skill_1_name',
            field=models.CharField(choices=[('Barter', 'Barter'), ('Energy Weapons', 'Energy Weapons'), ('Explosives', 'Explosives'), ('Guns', 'Guns'), ('Medicine', 'Medicine'), ('Melee Weapons', 'Melee Weapons'), ('Repair', 'Repair'), ('Science', 'Science'), ('Sneak', 'Sneak'), ('Speech', 'Speech'), ('Survival', 'Survival'), ('Unarmed', 'Unarmed'), ('Not Required', 'Not Required')], default='Not Required', max_length=64),
        ),
        migrations.AlterField(
            model_name='perk',
            name='skill_2_name',
            field=models.CharField(choices=[('Barter', 'Barter'), ('Energy Weapons', 'Energy Weapons'), ('Explosives', 'Explosives'), ('Guns', 'Guns'), ('Medicine', 'Medicine'), ('Melee Weapons', 'Melee Weapons'), ('Repair', 'Repair'), ('Science', 'Science'), ('Sneak', 'Sneak'), ('Speech', 'Speech'), ('Survival', 'Survival'), ('Unarmed', 'Unarmed'), ('Not Required', 'Not Required')], default='Not Required', max_length=64),
        ),
        migrations.AlterField(
            model_name='perk',
            name='special_skill_1_name',
            field=models.CharField(choices=[('Strength', 'Strength'), ('Perception', 'Perception'), ('Endurance', 'Endurance'), ('Charisma', 'Charisma'), ('Intelligence', 'Intelligence'), ('Agility', 'Agility'), ('Luck', 'Luck'), ('Not Required', 'Not Required')], default='Not Required', max_length=64),
        ),
        migrations.AlterField(
            model_name='perk',
            name='special_skill_2_name',
            field=models.CharField(choices=[('Strength', 'Strength'), ('Perception', 'Perception'), ('Endurance', 'Endurance'), ('Charisma', 'Charisma'), ('Intelligence', 'Intelligence'), ('Agility', 'Agility'), ('Luck', 'Luck'), ('Not Required', 'Not Required')], default='Not Required', max_length=64),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='range',
            field=models.CharField(choices=[('Close', 'Close'), ('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long')], default='Close', max_length=64),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('Energy', 'Energy'), ('Guns', 'Guns'), ('Melee', 'Melee'), ('Unarmed', 'Unarmed')], default='Energy', max_length=64),
        ),
    ]
