# Generated by Django 4.2.6 on 2023-10-31 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falloutRpg', '0010_alter_armor_type_alter_character_karma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='other_effects',
            field=models.CharField(default='None', max_length=256),
        ),
        migrations.AlterField(
            model_name='character',
            name='rad_effects',
            field=models.CharField(default='None', max_length=64),
        ),
    ]
