# Generated by Django 4.2.6 on 2023-11-01 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falloutRpg', '0012_alter_character_action_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skill_lockpick',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
