# Generated by Django 4.2.6 on 2023-11-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falloutRpg', '0013_character_skill_lockpick'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
