# Generated by Django 4.2.6 on 2023-11-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('falloutRpg', '0014_inventory_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='perks',
            field=models.ManyToManyField(blank=True, to='falloutRpg.perk'),
        ),
    ]
