from django import forms
from django.contrib.auth.models import User
from .models import Character, Inventory_Item, Perk, Weapon, Armor
from django.utils.translation import gettext_lazy as _

class CharacterCreationForm(forms.ModelForm):
    class Meta:
        model = Character
        fields = [
            'name',
            'description',
            'backstory',
            'karma',
            'stat_strength',
            'stat_perception',
            'stat_endurance',
            'stat_charisma',
            'stat_intelligence',
            'stat_agility',
            'stat_luck',
            'skill_barter',
            'skill_energy_weapons',
            'skill_explosives',
            'skill_guns',
            'skill_lockpick',
            'skill_medicine',
            'skill_melee_weapons',
            'skill_repair',
            'skill_science',
            'skill_sneak',
            'skill_speech',
            'skill_survival',
            'skill_unarmed',
            'action_points',
            'poison_resistance',
            'radiation_resistance',
            'critical_chance',
            'hit_points',
        ]

        labels = {
            "name": _("Name"),
            "description": _("Description"),
            "backstory": _("Backstory"),
            "karma": _("Karma"),
            "stat_strength": _("Strength"),
            "stat_perception": _("Perception"),
            "stat_endurance": _("Endurance"),
            "stat_charisma": _("Charisma"),
            "stat_intelligence": _("Intelligence"),
            "stat_agility": _("Agility"),
            "stat_luck": _("Luck"),
            "skill_barter": _("Barter"),
            "skill_energy_weapons": _("Energy Weapons"),
            "skill_explosives": _("Explosives"),
            "skill_guns": _("Guns"),
            "skill_lockpick": _("Lockpick"),
            "skill_medicine": _("Science"),
            "skill_melee_weapons": _("Melee Weapons"),
            "skill_repair": _("Repair"),
            "skill_science": _("Science"),
            "skill_sneak": _("Sneak"),
            "skill_speech": _("Speech"),
            "skill_survival": _("Survival"),
            "skill_unarmed": _("Unarmed"),
            "action_points": _("Action Points"),
            "poison_resistance": _("Poison Resistance"),
            "radiation_resistance": _("Radiation Resistance"),
            "critical_chance'": _("Critical Chance"),
            "hit_points": _("Hit Points"),
        }
        help_texts = {
            "name": _("Your character's name."),
            "description": _("How your character looks."),
            "backstory": _("Your character's backstory."),
            "karma": _("Your character's alignment."),
            "stat_strength": _("A measure of your raw physical strength."),
            "stat_perception": _("How well you use your five senses, and also pertains to a 'sixth sense'."),
            "stat_endurance": _("Your health and overall physical fitness."),
            "stat_charisma": _("	Your overall attractiveness and likeability."),
            "stat_intelligence": _("Your basic intellect, curiosity in the world and adeptness at critical thinking."),
            "stat_agility": _("A measure of your quickness and dexterity."),
            "stat_luck": _("How often good things happen to you by chance."),
            "skill_barter": _("Initial level = 2 + (Charisma x 2) + (Luck / 2)"),
            "skill_energy_weapons": _("Initial level = 2 + (Perception x 2) + (Luck / 2)"),
            "skill_explosives": _("Initial level = 2 + (Perception x 2) + (Luck / 2)"),
            "skill_guns": _("Initial level = 2 + (Agility x 2) + (Luck / 2)"),
            "skill_lockpick": _("Initial level = 2 + (Perception x 2) + (Luck / 2)"),
            "skill_medicine": _("Initial level = 2 + (Intelligence x 2) + (Luck / 2)"),
            "skill_melee_weapons": _("Initial level = 2 + (Strength x 2) + (Luck / 2)"),
            "skill_repair": _("Initial level = 2 + (Intelligence x 2) + (Luck / 2)"),
            "skill_science": _("Initial level = 2 + (Intelligence x 2) + (Luck / 2)"),
            "skill_sneak": _("Initial level = 2 + (Agility x 2) + (Luck / 2)"),
            "skill_speech": _("Initial level = 2 + (Charisma x 2) + (Luck / 2)"),
            "skill_survival": _("Initial level = 2 + (Endurance x 2) + (Luck / 2)"),
            "skill_unarmed": _("Initial level = 2 + (Endurance x 2) + (Luck / 2)"),
            "action_points": _("Initial level = 65 + (Agility x 3)"),
            "poison_resistance": _("Initial level = (Endurance x 5) - 5"),
            "radiation_resistance": _("Initial level = (Endurance x 2) - 2"),
            "critical_chance'": _("Initial level = Luck"),
            "hit_points": _("Initial level = 95 + (Endurance x 20) + (Level x 5)"),
        }
